### ISSUE TITLE
Release checklist for v 1.0

### ISSUE THREAD

**Issue by paarandika** [scorelab/Bassa#10]
- [x] Solve database write issue
- [x] Refine authentication, rating and flagging of inappropriate content
- [ ] Automatic suggestions before new downloads
- [ ] Refine disk cleaning method 
- [x] Finish front-end
- [ ] Docker and Vagrant images for deployment

As an additional task, if we have enough time, we can look in to identifying inappropriate downloads.
